{
 "title": "Experiment dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "hello_world, example-voting-app_vote_1"
   },
   { "name": "rate", "query": "30s, 60s, 5m, 30m, 1h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "HTTP latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(http_request_latency_ms_sum{job=\"$container\"}[$rate]))",
     "legendFormat": "HTTP latency"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=\"$container\"}[$rate]))",
     "legendFormat": "receive"
    },
    {
     "expr": "-sum by (name) (rate(container_network_transmit_bytes_total{name=\"$container\"}[$rate]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Rate of syscalls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (syscall) (rate(syscall_counter_total{syscall!~\"---.*\", job=\"$container\"}[$rate]))",
     "legendFormat": "{{syscall}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=\"$container\"}[$rate]))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"$container\"}",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (response_code) (rate(http_request_total{job=\"$container\"}[$rate]))",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "IO rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_io_time_seconds_total{name=\"$container\"}[$rate]))",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}