# Configuration
BASE_NAME = 'se.kth.chaosorca'
NETM_NAME = '%s.netm' % BASE_NAME
SYSM_NAME = '%s.sysm' % BASE_NAME
SYSC_NAME = '%s.sysc' % BASE_NAME

PROMETHEUS_NAME = '%s.prometheus' % BASE_NAME
PROMETHEUS_PORT = '9090'

GRAFANA_PORT = '3000'
GF_SECURITY_ADMIN_PASSWORD = 'foobar'
GF_USERS_ALLOW_SIGN_UP = 'false'

MONITORING_NETWORK_NAME = PROMETHEUS_NAME
MONITORING_DEFAULT_PORT = '12301'

LOG_FAILED = '❌ FAILED'
LOG_SUCCESS = '✔️ SUCCESS'
